### ISSUE TITLE
Port project to Godot 4

### ISSUE THREAD

**Issue by JAWS81** [gdquest-demos/godot-shaders#48]

**Comment by IceflowRE** [comment]
Duplicate  #47.

**Comment by Zifai** [comment]
Please update

**Comment by Reneator** [comment]
I am using an old version of the outline shader and it stopped working with godot 4, i stumbled on a solution that should work with many of the shaders from this repo (mostly regarding fragment functions):

https://github.com/godotengine/godot/issues/49781

TL;DR: Many of the shaders can be fixed when setting color by using a "COLOR *=" instead of "COLOR =", because it seems the values are different now.


Maybe leaving this one up so people could stumble upon this could be helpful.

**Comment by Reneator** [comment]
The tip above is mostly meant to fix the "modulate set on a canvasItem gets ignored when shader is applied" and to then also be able to draw outside the texture you might need something along the lines of:

```	
if (color.a <= 0.0) {
  COLOR = mix(color, line_color, outline - color.a);
}
else {
  COLOR *= mix(color, line_color, outline - color.a);
}
```

**Comment by NathanLovato** [comment]
If someone would like to contribute, this would be most welcome. I won't have time to port this myself anytime soon.

**Comment by tetrapod00** [comment]
I can try porting some of these. I'd recommend choosing 4.3 as the lowest supported version, if you have any shaders that read from the depth texture, since 4.3 is the first version after [Reverse-Z](https://godotengine.org/article/introducing-reverse-z/).

**Comment by NathanLovato** [comment]
Closing in favor of #53 to help coordinate work
